[build]
builder = "dockerfile"

[deploy]
startCommand = "./build/server"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
PORT = "9000"
CORS_ORIGIN = "https://frontend-n8xu99dr3-segfals-projects.vercel.app"
