name: Deploy to Railway

on:
  push:
    branches: [ main, develop, feature/vercel-railway-deployment ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.19.0'
  Emscripten_VERSION: '3.1.45'

jobs:
  validate-and-deploy-backend:
    name: Validate & Deploy Backend to Railway
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Run backend validation
      working-directory: ./websocket-server
      run: |
        chmod +x build.sh
        ./build.sh
        
    - name: Deploy WebSocket Server to Railway
      working-directory: ./websocket-server
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        # Install Railway CLI
        npm install -g @railway/cli@latest
        
        # Login to Railway
        railway login --token $RAILWAY_TOKEN
        
        # Deploy to Railway
        railway up --service websocket-server
        
    - name: Deploy ML Service to Railway
      working-directory: ./ml_shapes
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        # Install Railway CLI (if not already installed)
        npm install -g @railway/cli@latest
        
        # Login to Railway
        railway login --token $RAILWAY_TOKEN
        
        # Deploy ML service
        railway up --service ml-service
        
    - name: Wait for services to be ready
      run: |
        echo "Waiting for Railway services to be ready..."
        sleep 30
        
    - name: Test WebSocket Server health
      run: |
        # Get the Railway URL from environment or secrets
        WEBSOCKET_URL="${{ secrets.RAILWAY_WEBSOCKET_URL }}"
        
        # Test health endpoint
        curl -f "$WEBSOCKET_URL/health" || {
          echo "WebSocket server health check failed"
          exit 1
        }
        
    - name: Test ML Service health
      run: |
        # Get the Railway URL from environment or secrets
        ML_URL="${{ secrets.RAILWAY_ML_URL }}"
        
        # Test health endpoint
        curl -f "$ML_URL/health" || {
          echo "ML service health check failed"
          exit 1
        }
        
    - name: Comment PR with deployment status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const websocketUrl = `${{ secrets.RAILWAY_WEBSOCKET_URL }}`;
          const mlUrl = `${{ secrets.RAILWAY_ML_URL }}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚂 **Backend deployed to Railway!**\n\n🔗 **WebSocket Server:** ${websocketUrl}\n🔗 **ML Service:** ${mlUrl}\n\n✅ All validations passed\n\nServices are ready for testing.`
          });
